import json

scripts_dict = {
    "map_request" : {
        "Name" : "Map Request",
        "Status" : "NA",
        "Schedule Type" : "Minute",
        "Scheduled Frequency" : "5",
        "Scheduled Date" : "",
        "Scheduled Time" : ":00",
        "Previous Attempt" : "",
        "Last Successful Attempt" : "",
        "Errors" : "",
        "Error String" : "",
    },
    "update_jetter_status" : {
        "Name" : "Update Jetter Status",
        "Status" : "NA",
        "Schedule Type" : "Day",
        "Scheduled Frequency" : "12",
        "Scheduled Date" : "",
        "Scheduled Time" : ["09:20", "12:00"],
        "Previous Attempt" : "",
        "Last Successful Attempt" : "",
        "Errors" : "",
        "Error String" : "",
    },
    "update_valve_status" : {
        "Name" : "Update Valve Status",
        "Status" : "NA",
        "Schedule Type" : "Day",
        "Scheduled Frequency" : "12",
        "Scheduled Date" : "",
        "Scheduled Time" : ["09:20", "12:00"],
        "Previous Attempt" : "",
        "Last Successful Attempt" : "",
        "Errors" : "",
        "Error String" : "",
    },
    "update_hydrant_status" : {
        "Name" : "Update Hydrant Status",
        "Status" : "NA",
        "Schedule Type" : "Day",
        "Scheduled Frequency" : "12",
        "Scheduled Date" : "",
        "Scheduled Time" : ["09:20", "12:00"],
        "Previous Attempt" : "",
        "Last Successful Attempt" : "",
        "Errors" : "",
        "Error String" : "",
    },
    "update_watermainbreak_status" : {
        "Name" : "Update WatermainBreak Status",
        "Status" : "NA",
        "Schedule Type" : "Day",
        "Scheduled Frequency" : "12",
        "Scheduled Date" : "",
        "Scheduled Time" : ["09:20", "12:00"],
        "Previous Attempt" : "",
        "Last Successful Attempt" : "",
        "Errors" : "",
        "Error String" : "",
    },
}

with open("W:\GIS\Python\Scheduler\Scripts.json","w") as f:
    json.dump(scripts_dict,f, indent=4, separators=(',', ': '))
